### ISSUE TITLE
Mapper start-up

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#5]
The controller needs to be able to import the mapping code, then call a function that kicks off the mapper's work and returns a collection of waypoints and a static map object. The waypoint data will be copied to a shared data structure, which will be shared between other processes. The static map data will be passed to the localizer when it is first called.

**Comment by rlsnow** [comment]
Ok, Thanks for the update.  I'm hoping to have this stuff implemented by Friday.  For now, if there's a need, you could just call my make map function and make the map directly instead of importing.  It takes a few seconds to populate the map but if you need to do some testing or something it should work.  

Hopefully by Friday I will have the numpy implementation of the map, have way-points calculated, and have a pickling and unpickling routine that returns the static map and way-points.

**Comment by napratin** [comment]
NumPy has some built-in save/load functionality that you might want to look into:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html

It shouldn't change the rest of your code; only the arrays will be stored in NumPy's custom format (which I believe is more efficient, and has some optimizations that make it better than simple pickling). One advantage might be the zipped storage function savez() that can cut down on file size if required.

**Comment by dfarrell07** [comment]
Mapper now gives controller waypoints, the course_map and the map_properties successfully.
